#!/usr/bin/env bash

read -p "Digite seu nome: " name
read -p "Digite seu email: " email

git config --global user.name "${name}"
git config --global user.email "${email}"

user=$(whoami)

ssh-keygen -t ed25519 -N "" -f ~/.ssh/id_ed25519 -C "$user@prova"

RED='\033[0;31m'
NC='\033[0m' # No Color
echo -e "${RED}ATENÇÃO!${NC}"
echo "Acesse o Github em: Configurations > SSH and GPG keys > New SSH key"
echo "Em 'title' coloque o que quiser."
echo "Em 'key' cole sua chave pública:"
cat ~/.ssh/id_ed25519.pub
